### ISSUE TITLE
Compatibility with the survive mod.

### ISSUE THREAD

**Issue by ghost** [ElenaiDev/ElenaiDodge2.0#39]
The dodge bar overlaps the survive mod's thirst meter. It isn't a game breaking bug but it can be quite annoying.

**Comment by ElenaiDev** [comment]
Hi there!

I've messaged the author of Survive about this issue in the past, and have even given them the code for a simple fix as this issue is on their end not mine. Either they haven't seen this or haven't gotten around to fixing this yet (which is completely understandable as development can get especially overwhelming), however there is little more I can do to help.

However, I have just finished programming the option to configure the height of Elenai Dodge 2's GUI manually in the mod config, allowing you to simply move my feather bar upwards. This update will be coming out either this or next week. 

As development in the new update for this bug has been finished, I'll close the issue for now :)

Have a great day!
Elenai <3
